import localFont from "next/font/local";
import "./globals.css";
import {Inter} from "next/font/google"
import StoreProvider from "./StoreProvider";
import { ModeToggle } from "../components/Mode-Toggle";
import { ThemeProvider } from "../components/theme-provider";
import { Toaster } from "../../@/components/ui/toaster"
import { cn } from "../lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(`${inter.className}   antialiased  min-w-screen relative min-h-screen`)}
      >
        <StoreProvider>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          > 
          <div className="">
            <ModeToggle></ModeToggle>
          </div>
          
            {children}
            <Toaster className="bottom-5 left-5"/>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
